### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/StockSignals#74]
Congratulations on finishing milestone 3 group 5!  Nice work uploading your package to PYPI! Nice work on the Tests on R and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

Great job your Rpackage tests all passed

- [ ] Branch names are very hard to understand  -2 Mechanics

<img width="365" alt="Screenshot 2023-01-30 at 3 39 19 PM" src="https://user-images.githubusercontent.com/45893111/215622743-3c413df3-41a8-4a62-a590-b247149eff5b.png">

Python Package

Usage doc on the readme file is very hard to understand. 

- [ ] The documentation lacks of a demostration - -3 reasoning

- [ ] The documentation build with ReadtheDocs is not available (no link on GitHub or in the README.md file) - -2 reasoning

- [ ] The README.md is not specifying how to download the package from PyPI - -2 reasoning

Branch names are very hard to understand 
-2 Mechanics

Great job, you’re at the final stretch. One milestone left :)

**Comment by robindhillon1** [comment]
Hi Andy, we just talked to Glenn and Florencia during lab and they told us to fix all of these. These were fixed about 45 minutes ago. Please see commit here: https://github.com/UBC-MDS/StockSignals/commit/71fd95ecb6498f1ca4980eaef7ba2fb5cf581fb4

Again, we talked to both of them and they said we can fix the usage section, which we promptly did. Please look at these again; a regrade is we'd greatly appreciated. We were told that marking would probably not be done this soon, hence we fixed this stuff asap. 

Also, is there a -7 for not including a link only? This is not a requirement in the milestone 3 instructions. The documentation is done properly on ReadTheDocs: https://stocksignals.readthedocs.io/

**Comment by andytai7** [comment]
Hi @robindhillon1 

I've spoken with Florencia, it seems as though you had spoken to Glenn and Florencia about the tests for the python package for milestone 2? This does not apply to milestone 3, so i'm confused about what you are taking

**Comment by andytai7** [comment]
Hi @robindhillon1 

I just had a chat to Florencia about this. It seems as though the chat with Glenn and Florencia was about the pythons tests for Milestone 2. I am not sure how that is relevant for the notes i've given for Milestone 3. I did not check the python tests for from Milestone 2. 

Above, it seems as though the Python Package still does not have read the docs linked. This is crucial as no one would know where to find this on the readme. Please let me know what else i can clarify.

**Comment by robindhillon1** [comment]
Hi @andytai7 , I have added `ReadTheDocs` link to the readme right now and merged it with main. Please take a look. I was just waiting for your follow up to add the link as I didn't want to add it without your approval first. Thanks for clarifying.

**Comment by andytai7** [comment]
Hi @robindhillon1, as a result, i will be taking off 2 marks instead of 5 for that mistake before. I hope this helps.
